# Generated by Django 4.2.24 on 2025-09-25 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='adresse_arrivee',
            field=models.TextField(default=None, max_length=500, verbose_name="Adresse d'arrivée"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='bagages',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Nombre de bagages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='heure_aller',
            field=models.TimeField(default=None, verbose_name='Heure aller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='heure_retour',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure retour'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='nb_passagers',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Nombre de passagers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='vehicule',
            field=models.CharField(choices=[('berline', 'Berline'), ('utilitaire', 'Utilitaire')], default=None, max_length=20, verbose_name='Type de véhicule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trajet',
            name='adresse_depart',
            field=models.TextField(max_length=500, verbose_name='Adresse de départ'),
        ),
    ]
