# Generated by Django 4.2.24 on 2025-10-07 12:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_trajet_adresse_arrivee_trajet_bagages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='heure_aller',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='heure_retour',
        ),
        migrations.AddField(
            model_name='trajet',
            name='date_aller',
            field=models.DateField(default=datetime.datetime(2025, 10, 7, 14, 42, 13, 931424), verbose_name='Date aller'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='date_retour',
            field=models.DateField(blank=True, null=True, verbose_name='Date retour'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='adresse_arrivee',
            field=models.TextField(default='Valence, France', max_length=500, verbose_name="Adresse d'arrivée"),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='adresse_depart',
            field=models.TextField(default='Marseille, France', max_length=500, verbose_name='Adresse de départ'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='bagages',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Nombre de bagages'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='nb_passagers',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Nombre de passagers'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Heure de Demande'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='vehicule',
            field=models.CharField(choices=[('berline', 'Berline'), ('utilitaire', 'Utilitaire')], default='berline', max_length=20, verbose_name='Type de véhicule'),
        ),
    ]
