# Generated by Django 4.2.24 on 2025-10-07 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_trajet_heure_aller_remove_trajet_heure_retour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateField(default=datetime.datetime(2025, 10, 7, 14, 42, 27, 790678), verbose_name='Date aller'),
        ),
    ]
