# Generated by Django 4.2.24 on 2025-10-07 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateField(default=datetime.datetime(2025, 10, 7, 14, 46, 19, 509835), verbose_name='Date aller'),
        ),
    ]
