# Generated by Django 4.2.24 on 2025-10-07 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure aller'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure retour'),
        ),
    ]
