# Generated by Django 4.2.24 on 2025-10-07 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_trajet_date_aller_alter_trajet_date_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 14, 55, 42, 556364), verbose_name='Date et heure aller'),
        ),
    ]
