# Generated by Django 4.2.24 on 2025-10-07 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance (km)'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='duree_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Durée (minutes)'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 15, 1, 53, 896416), verbose_name='Date et heure aller'),
        ),
    ]
