# Generated by Django 4.2.24 on 2025-10-07 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_trajet_distance_km_trajet_duree_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 16, 0, 41, 759992), verbose_name='Date et heure aller'),
        ),
    ]
