# Generated by Django 4.2.24 on 2025-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-10-08T19:25:23', verbose_name='Date et heure aller'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='distance_km',
            field=models.IntegerField(default=0, verbose_name='Distance (km)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trajet',
            name='duree_min',
            field=models.IntegerField(default=0, verbose_name='Durée (minutes)'),
            preserve_default=False,
        ),
    ]
