# Generated by Django 4.2.24 on 2025-10-08 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_trajet_date_aller_alter_trajet_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-10-08T22:29:37', verbose_name='Date et heure aller'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='distance_km',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='duree_min',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2880)], verbose_name='Durée (minutes)'),
        ),
    ]
