# Generated by Django 4.2.24 on 2025-10-08 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_trajet_date_aller_alter_trajet_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='price_euros',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Prix (€)'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-10-08T22:42:27', verbose_name='Date et heure aller'),
        ),
    ]
