# Generated by Django 4.2.24 on 2025-10-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_trajet_price_euros_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-10-09T10:58:12', verbose_name='Date et heure aller'),
        ),
    ]
