# Generated by Django 4.2.24 on 2025-10-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-10-17T15:33:45', verbose_name='Date et heure de prise en charge'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de prise en charge retour'),
        ),
    ]
