# Generated by Django 4.2.24 on 2025-10-21 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_alter_trajet_date_aller_alter_trajet_date_retour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='bagages',
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-10-21T17:30:24', verbose_name='Date et heure de prise en charge'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='nb_passagers',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Nombre de passagers'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='vehicule',
            field=models.CharField(choices=[('berline', 'Polestar 2 - 2022 - coupé 4 portes')], default='berline', max_length=20, verbose_name='Type de véhicule'),
        ),
    ]
