# Generated by Django 4.2.24 on 2025-10-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_remove_trajet_bagages_alter_trajet_date_aller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-10-22T21:45:31', verbose_name='Date et heure de prise en charge'),
        ),
    ]
