# Generated by Django 4.2.24 on 2025-10-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-10-22T21:47:35', verbose_name='Date et heure de prise en charge'),
        ),
    ]
