# Generated by Django 4.2.24 on 2025-11-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='checkout_id',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='ID paiement sum up'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='checkout_reference',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Reference paiement sum up'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='checkout_status',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Status paiement sum up'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='adresse_depart',
            field=models.TextField(default='Pôle bus, Avenue Félix Faure, Valence, France', max_length=500, verbose_name='Adresse de départ'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-14T12:00:19', verbose_name='Date et heure de prise en charge'),
        ),
    ]
