# Generated by Django 4.2.24 on 2025-11-20 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_trajet_checkout_id_trajet_checkout_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('telephone_client', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format 06XXXXXXX.', regex='^0[1-9]\\d{8}$')])),
                ('email_client', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Format d’email invalide.')])),
                ('passagers', models.TextField(help_text='Format : Nom - Numéro, un par ligne.')),
                ('commentaire_client', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-20T11:37:12', verbose_name='Date et heure de prise en charge'),
        ),
    ]
