# Generated by Django 4.2.24 on 2025-11-20 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_contactclient_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactclient',
            name='email_client',
            field=models.EmailField(default='bonjour.bonjour@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator(message="Format d'email invalide.")]),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='nom_client',
            field=models.CharField(default='Mickael', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='passagers',
            field=models.TextField(default='Mme Durand - 0611122233, M. Martin - 064445556', help_text='Format : Nom numéro, Nom numéro, ...'),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='prenom_client',
            field=models.CharField(default='Jackson', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='telephone_client',
            field=models.CharField(default='0601020304', max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format 06XXXXXXX.', regex='^0[1-9]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-20T11:44:40', verbose_name='Date et heure de prise en charge'),
        ),
    ]
