# Generated by Django 4.2.24 on 2025-11-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_alter_contactclient_email_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-20T11:55:35', verbose_name='Date et heure de prise en charge'),
        ),
    ]
