# Generated by Django 4.2.24 on 2025-11-20 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactclient',
            name='commentaire_client',
        ),
        migrations.AddField(
            model_name='trajet',
            name='commentaire_client',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='telephone_client',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format 06XXXXXXX.', regex='^0[1-9]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-20T12:03:20', verbose_name='Date et heure de prise en charge'),
        ),
    ]
