# Generated by Django 4.2.24 on 2025-11-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_remove_contactclient_commentaire_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactclient',
            name='passagers',
            field=models.TextField(blank=True, default='Mme Durand - 0611122233, M. Martin - 064445556', help_text='Format : Nom numéro de téléphone, Nom numéro de téléphone, ...', null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-29T17:24:23', verbose_name='Date et heure de prise en charge'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_retour',
            field=models.DateTimeField(blank=True, help_text='Laisser vide si aller simple', null=True, verbose_name='Optionnel - Date et heure de prise en charge retour'),
        ),
    ]
