# Generated by Django 4.2.24 on 2025-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_alter_contactclient_passagers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-29T17:25:57', verbose_name='Date et heure de prise en charge'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_retour',
            field=models.DateTimeField(blank=True, help_text='Optionnel', null=True, verbose_name='Date et heure de prise en charge retour'),
        ),
    ]
