# Generated by Django 4.2.24 on 2025-11-29 16:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_alter_trajet_date_aller_alter_trajet_date_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-29T17:32:09', verbose_name='Date et heure de prise en charge'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='price_euros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10000.00'))], verbose_name='Prix (€)'),
        ),
    ]
