# Generated by Django 4.2.24 on 2025-11-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_alter_trajet_date_aller_alter_trajet_price_euros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-29T17:36:58', verbose_name='Date et heure de prise en charge'),
        ),
    ]
