# Generated by Django 4.2.24 on 2025-11-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0027_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-11-29T17:46:37', verbose_name='Date et heure de prise en charge'),
        ),
    ]
