# Generated by Django 4.2.24 on 2025-12-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0031_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='type_trajet',
            field=models.TextField(default='Aller Simple', max_length=50, verbose_name='Type de trajet'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-12-01T10:36:12', verbose_name='Date et heure de prise en charge'),
        ),
    ]
