# Generated by Django 4.2.24 on 2025-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0032_trajet_type_trajet_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-12-01T17:58:49', verbose_name='Date et heure de prise en charge'),
        ),
    ]
