# Generated by Django 4.2.24 on 2025-12-01 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0033_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trajet',
            old_name='duree_min',
            new_name='duree_min_aller',
        ),
        migrations.AddField(
            model_name='trajet',
            name='duree_min_retour',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2880)], verbose_name='Durée (minutes)'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-12-01T18:01:31', verbose_name='Date et heure de prise en charge'),
        ),
    ]
