# Generated by Django 4.2.24 on 2025-12-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0034_rename_duree_min_trajet_duree_min_aller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-12-01T18:08:12', verbose_name='Date et heure de prise en charge'),
        ),
    ]
