# Generated by Django 4.2.24 on 2025-12-11 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0035_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactclient',
            name='email_client',
            field=models.EmailField(default='virgil.mesle@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator(message="Format d'email invalide.")]),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-12-11T16:31:36', verbose_name='Date et heure de prise en charge'),
        ),
    ]
