# Generated by Django 4.2.24 on 2025-12-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0036_alter_contactclient_email_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default='2025-12-11T16:35:10', verbose_name='Date et heure de prise en charge'),
        ),
    ]
