# Generated by Django 4.2.24 on 2025-12-11 21:42

import django.core.validators
from django.db import migrations, models
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0037_alter_trajet_date_aller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_aller',
            field=models.DateTimeField(default=reservations.models.default_date, verbose_name='Date et heure de prise en charge'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='duree_min_aller',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2880)], verbose_name='Durée Aller (minutes)'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='duree_min_retour',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2880)], verbose_name='Durée Retour (minutes)'),
        ),
    ]
