# Generated by Django 4.2.24 on 2025-12-11 21:44

from django.db import migrations, models
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0038_alter_trajet_date_aller_alter_trajet_duree_min_aller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='requested_at',
            field=models.DateTimeField(default=reservations.models.default_date, verbose_name='Heure de la Demande'),
        ),
    ]
