# Generated by Django 4.2.24 on 2025-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0039_alter_trajet_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactclient',
            name='client_adress',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
