# Generated by Django 4.2.24 on 2025-12-18 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0040_contactclient_client_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactclient',
            name='client_adress',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='email_client',
            field=models.EmailField(default='virgil.mesle@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator(message="Format d'email invalide.")], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='nom_client',
            field=models.CharField(default='Mickael', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='passagers',
            field=models.TextField(blank=True, default='Mme Durand - 0611122233, M. Martin - 064445556', help_text='Format : Nom numéro de téléphone, Nom numéro de téléphone, ...', null=True, verbose_name='Information sur les passagers'),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='prenom_client',
            field=models.CharField(default='Jackson', max_length=100, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='contactclient',
            name='telephone_client',
            field=models.CharField(default='0601020304', max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format 06XXXXXXX.', regex='^0[1-9]\\d{8}$')], verbose_name='Telephone'),
        ),
    ]
