# Generated by Django 4.2.24 on 2025-12-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0041_alter_contactclient_client_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_retour',
            field=models.DateTimeField(blank=True, help_text='Optionnel - Laisser vide pour un aller simple.', null=True, verbose_name='Date et heure de prise en charge retour'),
        ),
    ]
